# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simulation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10simulation.proto\x12\x08lastmile\"}\n\x08SimEvent\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x10\n\x08robot_id\x18\x03 \x01(\r\x12\t\n\x01x\x18\x04 \x01(\x02\x12\t\n\x01y\x18\x05 \x01(\x02\x12\x0f\n\x07\x62\x61ttery\x18\x06 \x01(\x02\x12\x0e\n\x06status\x18\x07 \x01(\t\x12\x0c\n\x04note\x18\x08 \x01(\t\"\xcd\x01\n\x08SimStats\x12\x18\n\x10total_deliveries\x18\x01 \x01(\r\x12\x18\n\x10total_energy_kwh\x18\x02 \x01(\x01\x12\x17\n\x0frecharge_events\x18\x03 \x01(\r\x12\x14\n\x0c\x66\x61iled_paths\x18\x04 \x01(\r\x12\x14\n\x0ctraffic_jams\x18\x05 \x01(\r\x12\x16\n\x0e\x64\x65livery_fails\x18\x06 \x01(\r\x12\x16\n\x0eweather_delays\x18\x07 \x01(\r\x12\x18\n\x10parallel_batches\x18\x08 \x01(\r\"\x8c\x01\n\tSimOutput\x12\"\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x12.lastmile.SimEvent\x12!\n\x05stats\x18\x02 \x01(\x0b\x32\x12.lastmile.SimStats\x12\x12\n\nnum_robots\x18\x03 \x01(\r\x12\x12\n\nduration_s\x18\x04 \x01(\x01\x12\x10\n\x08hub_mode\x18\x05 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simulation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIMEVENT._serialized_start=30
  _SIMEVENT._serialized_end=155
  _SIMSTATS._serialized_start=158
  _SIMSTATS._serialized_end=363
  _SIMOUTPUT._serialized_start=366
  _SIMOUTPUT._serialized_end=506
# @@protoc_insertion_point(module_scope)
