// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simulation.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_simulation_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_simulation_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_simulation_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_simulation_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_simulation_2eproto;
namespace lastmile {
class SimEvent;
struct SimEventDefaultTypeInternal;
extern SimEventDefaultTypeInternal _SimEvent_default_instance_;
class SimOutput;
struct SimOutputDefaultTypeInternal;
extern SimOutputDefaultTypeInternal _SimOutput_default_instance_;
class SimStats;
struct SimStatsDefaultTypeInternal;
extern SimStatsDefaultTypeInternal _SimStats_default_instance_;
}  // namespace lastmile
PROTOBUF_NAMESPACE_OPEN
template<> ::lastmile::SimEvent* Arena::CreateMaybeMessage<::lastmile::SimEvent>(Arena*);
template<> ::lastmile::SimOutput* Arena::CreateMaybeMessage<::lastmile::SimOutput>(Arena*);
template<> ::lastmile::SimStats* Arena::CreateMaybeMessage<::lastmile::SimStats>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace lastmile {

// ===================================================================

class SimEvent final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:lastmile.SimEvent) */ {
 public:
  inline SimEvent() : SimEvent(nullptr) {}
  ~SimEvent() override;
  explicit PROTOBUF_CONSTEXPR SimEvent(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SimEvent(const SimEvent& from);
  SimEvent(SimEvent&& from) noexcept
    : SimEvent() {
    *this = ::std::move(from);
  }

  inline SimEvent& operator=(const SimEvent& from) {
    CopyFrom(from);
    return *this;
  }
  inline SimEvent& operator=(SimEvent&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SimEvent& default_instance() {
    return *internal_default_instance();
  }
  static inline const SimEvent* internal_default_instance() {
    return reinterpret_cast<const SimEvent*>(
               &_SimEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SimEvent& a, SimEvent& b) {
    a.Swap(&b);
  }
  inline void Swap(SimEvent* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SimEvent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SimEvent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SimEvent>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SimEvent& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SimEvent& from) {
    SimEvent::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SimEvent* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "lastmile.SimEvent";
  }
  protected:
  explicit SimEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 2,
    kStatusFieldNumber = 7,
    kNoteFieldNumber = 8,
    kTimeFieldNumber = 1,
    kRobotIdFieldNumber = 3,
    kXFieldNumber = 4,
    kYFieldNumber = 5,
    kBatteryFieldNumber = 6,
  };
  // string type = 2;
  void clear_type();
  const std::string& type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_type();
  PROTOBUF_NODISCARD std::string* release_type();
  void set_allocated_type(std::string* type);
  private:
  const std::string& _internal_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_type(const std::string& value);
  std::string* _internal_mutable_type();
  public:

  // string status = 7;
  void clear_status();
  const std::string& status() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_status(ArgT0&& arg0, ArgT... args);
  std::string* mutable_status();
  PROTOBUF_NODISCARD std::string* release_status();
  void set_allocated_status(std::string* status);
  private:
  const std::string& _internal_status() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_status(const std::string& value);
  std::string* _internal_mutable_status();
  public:

  // string note = 8;
  void clear_note();
  const std::string& note() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_note(ArgT0&& arg0, ArgT... args);
  std::string* mutable_note();
  PROTOBUF_NODISCARD std::string* release_note();
  void set_allocated_note(std::string* note);
  private:
  const std::string& _internal_note() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_note(const std::string& value);
  std::string* _internal_mutable_note();
  public:

  // double time = 1;
  void clear_time();
  double time() const;
  void set_time(double value);
  private:
  double _internal_time() const;
  void _internal_set_time(double value);
  public:

  // uint32 robot_id = 3;
  void clear_robot_id();
  uint32_t robot_id() const;
  void set_robot_id(uint32_t value);
  private:
  uint32_t _internal_robot_id() const;
  void _internal_set_robot_id(uint32_t value);
  public:

  // float x = 4;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 5;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float battery = 6;
  void clear_battery();
  float battery() const;
  void set_battery(float value);
  private:
  float _internal_battery() const;
  void _internal_set_battery(float value);
  public:

  // @@protoc_insertion_point(class_scope:lastmile.SimEvent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr status_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr note_;
    double time_;
    uint32_t robot_id_;
    float x_;
    float y_;
    float battery_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_simulation_2eproto;
};
// -------------------------------------------------------------------

class SimStats final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:lastmile.SimStats) */ {
 public:
  inline SimStats() : SimStats(nullptr) {}
  ~SimStats() override;
  explicit PROTOBUF_CONSTEXPR SimStats(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SimStats(const SimStats& from);
  SimStats(SimStats&& from) noexcept
    : SimStats() {
    *this = ::std::move(from);
  }

  inline SimStats& operator=(const SimStats& from) {
    CopyFrom(from);
    return *this;
  }
  inline SimStats& operator=(SimStats&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SimStats& default_instance() {
    return *internal_default_instance();
  }
  static inline const SimStats* internal_default_instance() {
    return reinterpret_cast<const SimStats*>(
               &_SimStats_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SimStats& a, SimStats& b) {
    a.Swap(&b);
  }
  inline void Swap(SimStats* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SimStats* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SimStats* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SimStats>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SimStats& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SimStats& from) {
    SimStats::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SimStats* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "lastmile.SimStats";
  }
  protected:
  explicit SimStats(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTotalEnergyKwhFieldNumber = 2,
    kTotalDeliveriesFieldNumber = 1,
    kRechargeEventsFieldNumber = 3,
    kFailedPathsFieldNumber = 4,
    kTrafficJamsFieldNumber = 5,
    kDeliveryFailsFieldNumber = 6,
    kWeatherDelaysFieldNumber = 7,
    kParallelBatchesFieldNumber = 8,
  };
  // double total_energy_kwh = 2;
  void clear_total_energy_kwh();
  double total_energy_kwh() const;
  void set_total_energy_kwh(double value);
  private:
  double _internal_total_energy_kwh() const;
  void _internal_set_total_energy_kwh(double value);
  public:

  // uint32 total_deliveries = 1;
  void clear_total_deliveries();
  uint32_t total_deliveries() const;
  void set_total_deliveries(uint32_t value);
  private:
  uint32_t _internal_total_deliveries() const;
  void _internal_set_total_deliveries(uint32_t value);
  public:

  // uint32 recharge_events = 3;
  void clear_recharge_events();
  uint32_t recharge_events() const;
  void set_recharge_events(uint32_t value);
  private:
  uint32_t _internal_recharge_events() const;
  void _internal_set_recharge_events(uint32_t value);
  public:

  // uint32 failed_paths = 4;
  void clear_failed_paths();
  uint32_t failed_paths() const;
  void set_failed_paths(uint32_t value);
  private:
  uint32_t _internal_failed_paths() const;
  void _internal_set_failed_paths(uint32_t value);
  public:

  // uint32 traffic_jams = 5;
  void clear_traffic_jams();
  uint32_t traffic_jams() const;
  void set_traffic_jams(uint32_t value);
  private:
  uint32_t _internal_traffic_jams() const;
  void _internal_set_traffic_jams(uint32_t value);
  public:

  // uint32 delivery_fails = 6;
  void clear_delivery_fails();
  uint32_t delivery_fails() const;
  void set_delivery_fails(uint32_t value);
  private:
  uint32_t _internal_delivery_fails() const;
  void _internal_set_delivery_fails(uint32_t value);
  public:

  // uint32 weather_delays = 7;
  void clear_weather_delays();
  uint32_t weather_delays() const;
  void set_weather_delays(uint32_t value);
  private:
  uint32_t _internal_weather_delays() const;
  void _internal_set_weather_delays(uint32_t value);
  public:

  // uint32 parallel_batches = 8;
  void clear_parallel_batches();
  uint32_t parallel_batches() const;
  void set_parallel_batches(uint32_t value);
  private:
  uint32_t _internal_parallel_batches() const;
  void _internal_set_parallel_batches(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:lastmile.SimStats)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    double total_energy_kwh_;
    uint32_t total_deliveries_;
    uint32_t recharge_events_;
    uint32_t failed_paths_;
    uint32_t traffic_jams_;
    uint32_t delivery_fails_;
    uint32_t weather_delays_;
    uint32_t parallel_batches_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_simulation_2eproto;
};
// -------------------------------------------------------------------

class SimOutput final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:lastmile.SimOutput) */ {
 public:
  inline SimOutput() : SimOutput(nullptr) {}
  ~SimOutput() override;
  explicit PROTOBUF_CONSTEXPR SimOutput(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SimOutput(const SimOutput& from);
  SimOutput(SimOutput&& from) noexcept
    : SimOutput() {
    *this = ::std::move(from);
  }

  inline SimOutput& operator=(const SimOutput& from) {
    CopyFrom(from);
    return *this;
  }
  inline SimOutput& operator=(SimOutput&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SimOutput& default_instance() {
    return *internal_default_instance();
  }
  static inline const SimOutput* internal_default_instance() {
    return reinterpret_cast<const SimOutput*>(
               &_SimOutput_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SimOutput& a, SimOutput& b) {
    a.Swap(&b);
  }
  inline void Swap(SimOutput* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SimOutput* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SimOutput* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SimOutput>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SimOutput& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SimOutput& from) {
    SimOutput::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SimOutput* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "lastmile.SimOutput";
  }
  protected:
  explicit SimOutput(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEventsFieldNumber = 1,
    kHubModeFieldNumber = 5,
    kStatsFieldNumber = 2,
    kDurationSFieldNumber = 4,
    kNumRobotsFieldNumber = 3,
  };
  // repeated .lastmile.SimEvent events = 1;
  int events_size() const;
  private:
  int _internal_events_size() const;
  public:
  void clear_events();
  ::lastmile::SimEvent* mutable_events(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lastmile::SimEvent >*
      mutable_events();
  private:
  const ::lastmile::SimEvent& _internal_events(int index) const;
  ::lastmile::SimEvent* _internal_add_events();
  public:
  const ::lastmile::SimEvent& events(int index) const;
  ::lastmile::SimEvent* add_events();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lastmile::SimEvent >&
      events() const;

  // string hub_mode = 5;
  void clear_hub_mode();
  const std::string& hub_mode() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_hub_mode(ArgT0&& arg0, ArgT... args);
  std::string* mutable_hub_mode();
  PROTOBUF_NODISCARD std::string* release_hub_mode();
  void set_allocated_hub_mode(std::string* hub_mode);
  private:
  const std::string& _internal_hub_mode() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_hub_mode(const std::string& value);
  std::string* _internal_mutable_hub_mode();
  public:

  // .lastmile.SimStats stats = 2;
  bool has_stats() const;
  private:
  bool _internal_has_stats() const;
  public:
  void clear_stats();
  const ::lastmile::SimStats& stats() const;
  PROTOBUF_NODISCARD ::lastmile::SimStats* release_stats();
  ::lastmile::SimStats* mutable_stats();
  void set_allocated_stats(::lastmile::SimStats* stats);
  private:
  const ::lastmile::SimStats& _internal_stats() const;
  ::lastmile::SimStats* _internal_mutable_stats();
  public:
  void unsafe_arena_set_allocated_stats(
      ::lastmile::SimStats* stats);
  ::lastmile::SimStats* unsafe_arena_release_stats();

  // double duration_s = 4;
  void clear_duration_s();
  double duration_s() const;
  void set_duration_s(double value);
  private:
  double _internal_duration_s() const;
  void _internal_set_duration_s(double value);
  public:

  // uint32 num_robots = 3;
  void clear_num_robots();
  uint32_t num_robots() const;
  void set_num_robots(uint32_t value);
  private:
  uint32_t _internal_num_robots() const;
  void _internal_set_num_robots(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:lastmile.SimOutput)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lastmile::SimEvent > events_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr hub_mode_;
    ::lastmile::SimStats* stats_;
    double duration_s_;
    uint32_t num_robots_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_simulation_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SimEvent

// double time = 1;
inline void SimEvent::clear_time() {
  _impl_.time_ = 0;
}
inline double SimEvent::_internal_time() const {
  return _impl_.time_;
}
inline double SimEvent::time() const {
  // @@protoc_insertion_point(field_get:lastmile.SimEvent.time)
  return _internal_time();
}
inline void SimEvent::_internal_set_time(double value) {
  
  _impl_.time_ = value;
}
inline void SimEvent::set_time(double value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:lastmile.SimEvent.time)
}

// string type = 2;
inline void SimEvent::clear_type() {
  _impl_.type_.ClearToEmpty();
}
inline const std::string& SimEvent::type() const {
  // @@protoc_insertion_point(field_get:lastmile.SimEvent.type)
  return _internal_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SimEvent::set_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:lastmile.SimEvent.type)
}
inline std::string* SimEvent::mutable_type() {
  std::string* _s = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:lastmile.SimEvent.type)
  return _s;
}
inline const std::string& SimEvent::_internal_type() const {
  return _impl_.type_.Get();
}
inline void SimEvent::_internal_set_type(const std::string& value) {
  
  _impl_.type_.Set(value, GetArenaForAllocation());
}
inline std::string* SimEvent::_internal_mutable_type() {
  
  return _impl_.type_.Mutable(GetArenaForAllocation());
}
inline std::string* SimEvent::release_type() {
  // @@protoc_insertion_point(field_release:lastmile.SimEvent.type)
  return _impl_.type_.Release();
}
inline void SimEvent::set_allocated_type(std::string* type) {
  if (type != nullptr) {
    
  } else {
    
  }
  _impl_.type_.SetAllocated(type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.type_.IsDefault()) {
    _impl_.type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:lastmile.SimEvent.type)
}

// uint32 robot_id = 3;
inline void SimEvent::clear_robot_id() {
  _impl_.robot_id_ = 0u;
}
inline uint32_t SimEvent::_internal_robot_id() const {
  return _impl_.robot_id_;
}
inline uint32_t SimEvent::robot_id() const {
  // @@protoc_insertion_point(field_get:lastmile.SimEvent.robot_id)
  return _internal_robot_id();
}
inline void SimEvent::_internal_set_robot_id(uint32_t value) {
  
  _impl_.robot_id_ = value;
}
inline void SimEvent::set_robot_id(uint32_t value) {
  _internal_set_robot_id(value);
  // @@protoc_insertion_point(field_set:lastmile.SimEvent.robot_id)
}

// float x = 4;
inline void SimEvent::clear_x() {
  _impl_.x_ = 0;
}
inline float SimEvent::_internal_x() const {
  return _impl_.x_;
}
inline float SimEvent::x() const {
  // @@protoc_insertion_point(field_get:lastmile.SimEvent.x)
  return _internal_x();
}
inline void SimEvent::_internal_set_x(float value) {
  
  _impl_.x_ = value;
}
inline void SimEvent::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:lastmile.SimEvent.x)
}

// float y = 5;
inline void SimEvent::clear_y() {
  _impl_.y_ = 0;
}
inline float SimEvent::_internal_y() const {
  return _impl_.y_;
}
inline float SimEvent::y() const {
  // @@protoc_insertion_point(field_get:lastmile.SimEvent.y)
  return _internal_y();
}
inline void SimEvent::_internal_set_y(float value) {
  
  _impl_.y_ = value;
}
inline void SimEvent::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:lastmile.SimEvent.y)
}

// float battery = 6;
inline void SimEvent::clear_battery() {
  _impl_.battery_ = 0;
}
inline float SimEvent::_internal_battery() const {
  return _impl_.battery_;
}
inline float SimEvent::battery() const {
  // @@protoc_insertion_point(field_get:lastmile.SimEvent.battery)
  return _internal_battery();
}
inline void SimEvent::_internal_set_battery(float value) {
  
  _impl_.battery_ = value;
}
inline void SimEvent::set_battery(float value) {
  _internal_set_battery(value);
  // @@protoc_insertion_point(field_set:lastmile.SimEvent.battery)
}

// string status = 7;
inline void SimEvent::clear_status() {
  _impl_.status_.ClearToEmpty();
}
inline const std::string& SimEvent::status() const {
  // @@protoc_insertion_point(field_get:lastmile.SimEvent.status)
  return _internal_status();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SimEvent::set_status(ArgT0&& arg0, ArgT... args) {
 
 _impl_.status_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:lastmile.SimEvent.status)
}
inline std::string* SimEvent::mutable_status() {
  std::string* _s = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:lastmile.SimEvent.status)
  return _s;
}
inline const std::string& SimEvent::_internal_status() const {
  return _impl_.status_.Get();
}
inline void SimEvent::_internal_set_status(const std::string& value) {
  
  _impl_.status_.Set(value, GetArenaForAllocation());
}
inline std::string* SimEvent::_internal_mutable_status() {
  
  return _impl_.status_.Mutable(GetArenaForAllocation());
}
inline std::string* SimEvent::release_status() {
  // @@protoc_insertion_point(field_release:lastmile.SimEvent.status)
  return _impl_.status_.Release();
}
inline void SimEvent::set_allocated_status(std::string* status) {
  if (status != nullptr) {
    
  } else {
    
  }
  _impl_.status_.SetAllocated(status, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.status_.IsDefault()) {
    _impl_.status_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:lastmile.SimEvent.status)
}

// string note = 8;
inline void SimEvent::clear_note() {
  _impl_.note_.ClearToEmpty();
}
inline const std::string& SimEvent::note() const {
  // @@protoc_insertion_point(field_get:lastmile.SimEvent.note)
  return _internal_note();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SimEvent::set_note(ArgT0&& arg0, ArgT... args) {
 
 _impl_.note_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:lastmile.SimEvent.note)
}
inline std::string* SimEvent::mutable_note() {
  std::string* _s = _internal_mutable_note();
  // @@protoc_insertion_point(field_mutable:lastmile.SimEvent.note)
  return _s;
}
inline const std::string& SimEvent::_internal_note() const {
  return _impl_.note_.Get();
}
inline void SimEvent::_internal_set_note(const std::string& value) {
  
  _impl_.note_.Set(value, GetArenaForAllocation());
}
inline std::string* SimEvent::_internal_mutable_note() {
  
  return _impl_.note_.Mutable(GetArenaForAllocation());
}
inline std::string* SimEvent::release_note() {
  // @@protoc_insertion_point(field_release:lastmile.SimEvent.note)
  return _impl_.note_.Release();
}
inline void SimEvent::set_allocated_note(std::string* note) {
  if (note != nullptr) {
    
  } else {
    
  }
  _impl_.note_.SetAllocated(note, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.note_.IsDefault()) {
    _impl_.note_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:lastmile.SimEvent.note)
}

// -------------------------------------------------------------------

// SimStats

// uint32 total_deliveries = 1;
inline void SimStats::clear_total_deliveries() {
  _impl_.total_deliveries_ = 0u;
}
inline uint32_t SimStats::_internal_total_deliveries() const {
  return _impl_.total_deliveries_;
}
inline uint32_t SimStats::total_deliveries() const {
  // @@protoc_insertion_point(field_get:lastmile.SimStats.total_deliveries)
  return _internal_total_deliveries();
}
inline void SimStats::_internal_set_total_deliveries(uint32_t value) {
  
  _impl_.total_deliveries_ = value;
}
inline void SimStats::set_total_deliveries(uint32_t value) {
  _internal_set_total_deliveries(value);
  // @@protoc_insertion_point(field_set:lastmile.SimStats.total_deliveries)
}

// double total_energy_kwh = 2;
inline void SimStats::clear_total_energy_kwh() {
  _impl_.total_energy_kwh_ = 0;
}
inline double SimStats::_internal_total_energy_kwh() const {
  return _impl_.total_energy_kwh_;
}
inline double SimStats::total_energy_kwh() const {
  // @@protoc_insertion_point(field_get:lastmile.SimStats.total_energy_kwh)
  return _internal_total_energy_kwh();
}
inline void SimStats::_internal_set_total_energy_kwh(double value) {
  
  _impl_.total_energy_kwh_ = value;
}
inline void SimStats::set_total_energy_kwh(double value) {
  _internal_set_total_energy_kwh(value);
  // @@protoc_insertion_point(field_set:lastmile.SimStats.total_energy_kwh)
}

// uint32 recharge_events = 3;
inline void SimStats::clear_recharge_events() {
  _impl_.recharge_events_ = 0u;
}
inline uint32_t SimStats::_internal_recharge_events() const {
  return _impl_.recharge_events_;
}
inline uint32_t SimStats::recharge_events() const {
  // @@protoc_insertion_point(field_get:lastmile.SimStats.recharge_events)
  return _internal_recharge_events();
}
inline void SimStats::_internal_set_recharge_events(uint32_t value) {
  
  _impl_.recharge_events_ = value;
}
inline void SimStats::set_recharge_events(uint32_t value) {
  _internal_set_recharge_events(value);
  // @@protoc_insertion_point(field_set:lastmile.SimStats.recharge_events)
}

// uint32 failed_paths = 4;
inline void SimStats::clear_failed_paths() {
  _impl_.failed_paths_ = 0u;
}
inline uint32_t SimStats::_internal_failed_paths() const {
  return _impl_.failed_paths_;
}
inline uint32_t SimStats::failed_paths() const {
  // @@protoc_insertion_point(field_get:lastmile.SimStats.failed_paths)
  return _internal_failed_paths();
}
inline void SimStats::_internal_set_failed_paths(uint32_t value) {
  
  _impl_.failed_paths_ = value;
}
inline void SimStats::set_failed_paths(uint32_t value) {
  _internal_set_failed_paths(value);
  // @@protoc_insertion_point(field_set:lastmile.SimStats.failed_paths)
}

// uint32 traffic_jams = 5;
inline void SimStats::clear_traffic_jams() {
  _impl_.traffic_jams_ = 0u;
}
inline uint32_t SimStats::_internal_traffic_jams() const {
  return _impl_.traffic_jams_;
}
inline uint32_t SimStats::traffic_jams() const {
  // @@protoc_insertion_point(field_get:lastmile.SimStats.traffic_jams)
  return _internal_traffic_jams();
}
inline void SimStats::_internal_set_traffic_jams(uint32_t value) {
  
  _impl_.traffic_jams_ = value;
}
inline void SimStats::set_traffic_jams(uint32_t value) {
  _internal_set_traffic_jams(value);
  // @@protoc_insertion_point(field_set:lastmile.SimStats.traffic_jams)
}

// uint32 delivery_fails = 6;
inline void SimStats::clear_delivery_fails() {
  _impl_.delivery_fails_ = 0u;
}
inline uint32_t SimStats::_internal_delivery_fails() const {
  return _impl_.delivery_fails_;
}
inline uint32_t SimStats::delivery_fails() const {
  // @@protoc_insertion_point(field_get:lastmile.SimStats.delivery_fails)
  return _internal_delivery_fails();
}
inline void SimStats::_internal_set_delivery_fails(uint32_t value) {
  
  _impl_.delivery_fails_ = value;
}
inline void SimStats::set_delivery_fails(uint32_t value) {
  _internal_set_delivery_fails(value);
  // @@protoc_insertion_point(field_set:lastmile.SimStats.delivery_fails)
}

// uint32 weather_delays = 7;
inline void SimStats::clear_weather_delays() {
  _impl_.weather_delays_ = 0u;
}
inline uint32_t SimStats::_internal_weather_delays() const {
  return _impl_.weather_delays_;
}
inline uint32_t SimStats::weather_delays() const {
  // @@protoc_insertion_point(field_get:lastmile.SimStats.weather_delays)
  return _internal_weather_delays();
}
inline void SimStats::_internal_set_weather_delays(uint32_t value) {
  
  _impl_.weather_delays_ = value;
}
inline void SimStats::set_weather_delays(uint32_t value) {
  _internal_set_weather_delays(value);
  // @@protoc_insertion_point(field_set:lastmile.SimStats.weather_delays)
}

// uint32 parallel_batches = 8;
inline void SimStats::clear_parallel_batches() {
  _impl_.parallel_batches_ = 0u;
}
inline uint32_t SimStats::_internal_parallel_batches() const {
  return _impl_.parallel_batches_;
}
inline uint32_t SimStats::parallel_batches() const {
  // @@protoc_insertion_point(field_get:lastmile.SimStats.parallel_batches)
  return _internal_parallel_batches();
}
inline void SimStats::_internal_set_parallel_batches(uint32_t value) {
  
  _impl_.parallel_batches_ = value;
}
inline void SimStats::set_parallel_batches(uint32_t value) {
  _internal_set_parallel_batches(value);
  // @@protoc_insertion_point(field_set:lastmile.SimStats.parallel_batches)
}

// -------------------------------------------------------------------

// SimOutput

// repeated .lastmile.SimEvent events = 1;
inline int SimOutput::_internal_events_size() const {
  return _impl_.events_.size();
}
inline int SimOutput::events_size() const {
  return _internal_events_size();
}
inline void SimOutput::clear_events() {
  _impl_.events_.Clear();
}
inline ::lastmile::SimEvent* SimOutput::mutable_events(int index) {
  // @@protoc_insertion_point(field_mutable:lastmile.SimOutput.events)
  return _impl_.events_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lastmile::SimEvent >*
SimOutput::mutable_events() {
  // @@protoc_insertion_point(field_mutable_list:lastmile.SimOutput.events)
  return &_impl_.events_;
}
inline const ::lastmile::SimEvent& SimOutput::_internal_events(int index) const {
  return _impl_.events_.Get(index);
}
inline const ::lastmile::SimEvent& SimOutput::events(int index) const {
  // @@protoc_insertion_point(field_get:lastmile.SimOutput.events)
  return _internal_events(index);
}
inline ::lastmile::SimEvent* SimOutput::_internal_add_events() {
  return _impl_.events_.Add();
}
inline ::lastmile::SimEvent* SimOutput::add_events() {
  ::lastmile::SimEvent* _add = _internal_add_events();
  // @@protoc_insertion_point(field_add:lastmile.SimOutput.events)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::lastmile::SimEvent >&
SimOutput::events() const {
  // @@protoc_insertion_point(field_list:lastmile.SimOutput.events)
  return _impl_.events_;
}

// .lastmile.SimStats stats = 2;
inline bool SimOutput::_internal_has_stats() const {
  return this != internal_default_instance() && _impl_.stats_ != nullptr;
}
inline bool SimOutput::has_stats() const {
  return _internal_has_stats();
}
inline void SimOutput::clear_stats() {
  if (GetArenaForAllocation() == nullptr && _impl_.stats_ != nullptr) {
    delete _impl_.stats_;
  }
  _impl_.stats_ = nullptr;
}
inline const ::lastmile::SimStats& SimOutput::_internal_stats() const {
  const ::lastmile::SimStats* p = _impl_.stats_;
  return p != nullptr ? *p : reinterpret_cast<const ::lastmile::SimStats&>(
      ::lastmile::_SimStats_default_instance_);
}
inline const ::lastmile::SimStats& SimOutput::stats() const {
  // @@protoc_insertion_point(field_get:lastmile.SimOutput.stats)
  return _internal_stats();
}
inline void SimOutput::unsafe_arena_set_allocated_stats(
    ::lastmile::SimStats* stats) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.stats_);
  }
  _impl_.stats_ = stats;
  if (stats) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:lastmile.SimOutput.stats)
}
inline ::lastmile::SimStats* SimOutput::release_stats() {
  
  ::lastmile::SimStats* temp = _impl_.stats_;
  _impl_.stats_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::lastmile::SimStats* SimOutput::unsafe_arena_release_stats() {
  // @@protoc_insertion_point(field_release:lastmile.SimOutput.stats)
  
  ::lastmile::SimStats* temp = _impl_.stats_;
  _impl_.stats_ = nullptr;
  return temp;
}
inline ::lastmile::SimStats* SimOutput::_internal_mutable_stats() {
  
  if (_impl_.stats_ == nullptr) {
    auto* p = CreateMaybeMessage<::lastmile::SimStats>(GetArenaForAllocation());
    _impl_.stats_ = p;
  }
  return _impl_.stats_;
}
inline ::lastmile::SimStats* SimOutput::mutable_stats() {
  ::lastmile::SimStats* _msg = _internal_mutable_stats();
  // @@protoc_insertion_point(field_mutable:lastmile.SimOutput.stats)
  return _msg;
}
inline void SimOutput::set_allocated_stats(::lastmile::SimStats* stats) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.stats_;
  }
  if (stats) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(stats);
    if (message_arena != submessage_arena) {
      stats = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, stats, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.stats_ = stats;
  // @@protoc_insertion_point(field_set_allocated:lastmile.SimOutput.stats)
}

// uint32 num_robots = 3;
inline void SimOutput::clear_num_robots() {
  _impl_.num_robots_ = 0u;
}
inline uint32_t SimOutput::_internal_num_robots() const {
  return _impl_.num_robots_;
}
inline uint32_t SimOutput::num_robots() const {
  // @@protoc_insertion_point(field_get:lastmile.SimOutput.num_robots)
  return _internal_num_robots();
}
inline void SimOutput::_internal_set_num_robots(uint32_t value) {
  
  _impl_.num_robots_ = value;
}
inline void SimOutput::set_num_robots(uint32_t value) {
  _internal_set_num_robots(value);
  // @@protoc_insertion_point(field_set:lastmile.SimOutput.num_robots)
}

// double duration_s = 4;
inline void SimOutput::clear_duration_s() {
  _impl_.duration_s_ = 0;
}
inline double SimOutput::_internal_duration_s() const {
  return _impl_.duration_s_;
}
inline double SimOutput::duration_s() const {
  // @@protoc_insertion_point(field_get:lastmile.SimOutput.duration_s)
  return _internal_duration_s();
}
inline void SimOutput::_internal_set_duration_s(double value) {
  
  _impl_.duration_s_ = value;
}
inline void SimOutput::set_duration_s(double value) {
  _internal_set_duration_s(value);
  // @@protoc_insertion_point(field_set:lastmile.SimOutput.duration_s)
}

// string hub_mode = 5;
inline void SimOutput::clear_hub_mode() {
  _impl_.hub_mode_.ClearToEmpty();
}
inline const std::string& SimOutput::hub_mode() const {
  // @@protoc_insertion_point(field_get:lastmile.SimOutput.hub_mode)
  return _internal_hub_mode();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SimOutput::set_hub_mode(ArgT0&& arg0, ArgT... args) {
 
 _impl_.hub_mode_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:lastmile.SimOutput.hub_mode)
}
inline std::string* SimOutput::mutable_hub_mode() {
  std::string* _s = _internal_mutable_hub_mode();
  // @@protoc_insertion_point(field_mutable:lastmile.SimOutput.hub_mode)
  return _s;
}
inline const std::string& SimOutput::_internal_hub_mode() const {
  return _impl_.hub_mode_.Get();
}
inline void SimOutput::_internal_set_hub_mode(const std::string& value) {
  
  _impl_.hub_mode_.Set(value, GetArenaForAllocation());
}
inline std::string* SimOutput::_internal_mutable_hub_mode() {
  
  return _impl_.hub_mode_.Mutable(GetArenaForAllocation());
}
inline std::string* SimOutput::release_hub_mode() {
  // @@protoc_insertion_point(field_release:lastmile.SimOutput.hub_mode)
  return _impl_.hub_mode_.Release();
}
inline void SimOutput::set_allocated_hub_mode(std::string* hub_mode) {
  if (hub_mode != nullptr) {
    
  } else {
    
  }
  _impl_.hub_mode_.SetAllocated(hub_mode, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.hub_mode_.IsDefault()) {
    _impl_.hub_mode_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:lastmile.SimOutput.hub_mode)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace lastmile

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_simulation_2eproto
