// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simulation.proto

#include "simulation.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace lastmile {
PROTOBUF_CONSTEXPR SimEvent::SimEvent(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.status_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.note_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.time_)*/0
  , /*decltype(_impl_.robot_id_)*/0u
  , /*decltype(_impl_.x_)*/0
  , /*decltype(_impl_.y_)*/0
  , /*decltype(_impl_.battery_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SimEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SimEventDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SimEventDefaultTypeInternal() {}
  union {
    SimEvent _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SimEventDefaultTypeInternal _SimEvent_default_instance_;
PROTOBUF_CONSTEXPR SimStats::SimStats(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.total_energy_kwh_)*/0
  , /*decltype(_impl_.total_deliveries_)*/0u
  , /*decltype(_impl_.recharge_events_)*/0u
  , /*decltype(_impl_.failed_paths_)*/0u
  , /*decltype(_impl_.traffic_jams_)*/0u
  , /*decltype(_impl_.delivery_fails_)*/0u
  , /*decltype(_impl_.weather_delays_)*/0u
  , /*decltype(_impl_.parallel_batches_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SimStatsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SimStatsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SimStatsDefaultTypeInternal() {}
  union {
    SimStats _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SimStatsDefaultTypeInternal _SimStats_default_instance_;
PROTOBUF_CONSTEXPR SimOutput::SimOutput(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.events_)*/{}
  , /*decltype(_impl_.hub_mode_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.stats_)*/nullptr
  , /*decltype(_impl_.duration_s_)*/0
  , /*decltype(_impl_.num_robots_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SimOutputDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SimOutputDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SimOutputDefaultTypeInternal() {}
  union {
    SimOutput _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SimOutputDefaultTypeInternal _SimOutput_default_instance_;
}  // namespace lastmile
static ::_pb::Metadata file_level_metadata_simulation_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_simulation_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_simulation_2eproto = nullptr;

const uint32_t TableStruct_simulation_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::lastmile::SimEvent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::lastmile::SimEvent, _impl_.time_),
  PROTOBUF_FIELD_OFFSET(::lastmile::SimEvent, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::lastmile::SimEvent, _impl_.robot_id_),
  PROTOBUF_FIELD_OFFSET(::lastmile::SimEvent, _impl_.x_),
  PROTOBUF_FIELD_OFFSET(::lastmile::SimEvent, _impl_.y_),
  PROTOBUF_FIELD_OFFSET(::lastmile::SimEvent, _impl_.battery_),
  PROTOBUF_FIELD_OFFSET(::lastmile::SimEvent, _impl_.status_),
  PROTOBUF_FIELD_OFFSET(::lastmile::SimEvent, _impl_.note_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::lastmile::SimStats, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::lastmile::SimStats, _impl_.total_deliveries_),
  PROTOBUF_FIELD_OFFSET(::lastmile::SimStats, _impl_.total_energy_kwh_),
  PROTOBUF_FIELD_OFFSET(::lastmile::SimStats, _impl_.recharge_events_),
  PROTOBUF_FIELD_OFFSET(::lastmile::SimStats, _impl_.failed_paths_),
  PROTOBUF_FIELD_OFFSET(::lastmile::SimStats, _impl_.traffic_jams_),
  PROTOBUF_FIELD_OFFSET(::lastmile::SimStats, _impl_.delivery_fails_),
  PROTOBUF_FIELD_OFFSET(::lastmile::SimStats, _impl_.weather_delays_),
  PROTOBUF_FIELD_OFFSET(::lastmile::SimStats, _impl_.parallel_batches_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::lastmile::SimOutput, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::lastmile::SimOutput, _impl_.events_),
  PROTOBUF_FIELD_OFFSET(::lastmile::SimOutput, _impl_.stats_),
  PROTOBUF_FIELD_OFFSET(::lastmile::SimOutput, _impl_.num_robots_),
  PROTOBUF_FIELD_OFFSET(::lastmile::SimOutput, _impl_.duration_s_),
  PROTOBUF_FIELD_OFFSET(::lastmile::SimOutput, _impl_.hub_mode_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::lastmile::SimEvent)},
  { 14, -1, -1, sizeof(::lastmile::SimStats)},
  { 28, -1, -1, sizeof(::lastmile::SimOutput)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::lastmile::_SimEvent_default_instance_._instance,
  &::lastmile::_SimStats_default_instance_._instance,
  &::lastmile::_SimOutput_default_instance_._instance,
};

const char descriptor_table_protodef_simulation_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020simulation.proto\022\010lastmile\"}\n\010SimEvent"
  "\022\014\n\004time\030\001 \001(\001\022\014\n\004type\030\002 \001(\t\022\020\n\010robot_id"
  "\030\003 \001(\r\022\t\n\001x\030\004 \001(\002\022\t\n\001y\030\005 \001(\002\022\017\n\007battery\030"
  "\006 \001(\002\022\016\n\006status\030\007 \001(\t\022\014\n\004note\030\010 \001(\t\"\315\001\n\010"
  "SimStats\022\030\n\020total_deliveries\030\001 \001(\r\022\030\n\020to"
  "tal_energy_kwh\030\002 \001(\001\022\027\n\017recharge_events\030"
  "\003 \001(\r\022\024\n\014failed_paths\030\004 \001(\r\022\024\n\014traffic_j"
  "ams\030\005 \001(\r\022\026\n\016delivery_fails\030\006 \001(\r\022\026\n\016wea"
  "ther_delays\030\007 \001(\r\022\030\n\020parallel_batches\030\010 "
  "\001(\r\"\214\001\n\tSimOutput\022\"\n\006events\030\001 \003(\0132\022.last"
  "mile.SimEvent\022!\n\005stats\030\002 \001(\0132\022.lastmile."
  "SimStats\022\022\n\nnum_robots\030\003 \001(\r\022\022\n\nduration"
  "_s\030\004 \001(\001\022\020\n\010hub_mode\030\005 \001(\tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_simulation_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_simulation_2eproto = {
    false, false, 514, descriptor_table_protodef_simulation_2eproto,
    "simulation.proto",
    &descriptor_table_simulation_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_simulation_2eproto::offsets,
    file_level_metadata_simulation_2eproto, file_level_enum_descriptors_simulation_2eproto,
    file_level_service_descriptors_simulation_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_simulation_2eproto_getter() {
  return &descriptor_table_simulation_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_simulation_2eproto(&descriptor_table_simulation_2eproto);
namespace lastmile {

// ===================================================================

class SimEvent::_Internal {
 public:
};

SimEvent::SimEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:lastmile.SimEvent)
}
SimEvent::SimEvent(const SimEvent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SimEvent* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){}
    , decltype(_impl_.status_){}
    , decltype(_impl_.note_){}
    , decltype(_impl_.time_){}
    , decltype(_impl_.robot_id_){}
    , decltype(_impl_.x_){}
    , decltype(_impl_.y_){}
    , decltype(_impl_.battery_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_type().empty()) {
    _this->_impl_.type_.Set(from._internal_type(), 
      _this->GetArenaForAllocation());
  }
  _impl_.status_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.status_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_status().empty()) {
    _this->_impl_.status_.Set(from._internal_status(), 
      _this->GetArenaForAllocation());
  }
  _impl_.note_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.note_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_note().empty()) {
    _this->_impl_.note_.Set(from._internal_note(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.time_, &from._impl_.time_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.battery_) -
    reinterpret_cast<char*>(&_impl_.time_)) + sizeof(_impl_.battery_));
  // @@protoc_insertion_point(copy_constructor:lastmile.SimEvent)
}

inline void SimEvent::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.type_){}
    , decltype(_impl_.status_){}
    , decltype(_impl_.note_){}
    , decltype(_impl_.time_){0}
    , decltype(_impl_.robot_id_){0u}
    , decltype(_impl_.x_){0}
    , decltype(_impl_.y_){0}
    , decltype(_impl_.battery_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.status_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.status_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.note_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.note_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SimEvent::~SimEvent() {
  // @@protoc_insertion_point(destructor:lastmile.SimEvent)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SimEvent::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.type_.Destroy();
  _impl_.status_.Destroy();
  _impl_.note_.Destroy();
}

void SimEvent::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SimEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:lastmile.SimEvent)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.type_.ClearToEmpty();
  _impl_.status_.ClearToEmpty();
  _impl_.note_.ClearToEmpty();
  ::memset(&_impl_.time_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.battery_) -
      reinterpret_cast<char*>(&_impl_.time_)) + sizeof(_impl_.battery_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SimEvent::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double time = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _impl_.time_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // string type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "lastmile.SimEvent.type"));
        } else
          goto handle_unusual;
        continue;
      // uint32 robot_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.robot_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float x = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 37)) {
          _impl_.x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float y = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 45)) {
          _impl_.y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float battery = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 53)) {
          _impl_.battery_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // string status = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_status();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "lastmile.SimEvent.status"));
        } else
          goto handle_unusual;
        continue;
      // string note = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_note();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "lastmile.SimEvent.note"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SimEvent::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lastmile.SimEvent)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // double time = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_time = this->_internal_time();
  uint64_t raw_time;
  memcpy(&raw_time, &tmp_time, sizeof(tmp_time));
  if (raw_time != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_time(), target);
  }

  // string type = 2;
  if (!this->_internal_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_type().data(), static_cast<int>(this->_internal_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "lastmile.SimEvent.type");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_type(), target);
  }

  // uint32 robot_id = 3;
  if (this->_internal_robot_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_robot_id(), target);
  }

  // float x = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(4, this->_internal_x(), target);
  }

  // float y = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(5, this->_internal_y(), target);
  }

  // float battery = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_battery = this->_internal_battery();
  uint32_t raw_battery;
  memcpy(&raw_battery, &tmp_battery, sizeof(tmp_battery));
  if (raw_battery != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(6, this->_internal_battery(), target);
  }

  // string status = 7;
  if (!this->_internal_status().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_status().data(), static_cast<int>(this->_internal_status().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "lastmile.SimEvent.status");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_status(), target);
  }

  // string note = 8;
  if (!this->_internal_note().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_note().data(), static_cast<int>(this->_internal_note().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "lastmile.SimEvent.note");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_note(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lastmile.SimEvent)
  return target;
}

size_t SimEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lastmile.SimEvent)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string type = 2;
  if (!this->_internal_type().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_type());
  }

  // string status = 7;
  if (!this->_internal_status().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_status());
  }

  // string note = 8;
  if (!this->_internal_note().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_note());
  }

  // double time = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_time = this->_internal_time();
  uint64_t raw_time;
  memcpy(&raw_time, &tmp_time, sizeof(tmp_time));
  if (raw_time != 0) {
    total_size += 1 + 8;
  }

  // uint32 robot_id = 3;
  if (this->_internal_robot_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_robot_id());
  }

  // float x = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    total_size += 1 + 4;
  }

  // float y = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    total_size += 1 + 4;
  }

  // float battery = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_battery = this->_internal_battery();
  uint32_t raw_battery;
  memcpy(&raw_battery, &tmp_battery, sizeof(tmp_battery));
  if (raw_battery != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SimEvent::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SimEvent::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SimEvent::GetClassData() const { return &_class_data_; }


void SimEvent::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SimEvent*>(&to_msg);
  auto& from = static_cast<const SimEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lastmile.SimEvent)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_type().empty()) {
    _this->_internal_set_type(from._internal_type());
  }
  if (!from._internal_status().empty()) {
    _this->_internal_set_status(from._internal_status());
  }
  if (!from._internal_note().empty()) {
    _this->_internal_set_note(from._internal_note());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_time = from._internal_time();
  uint64_t raw_time;
  memcpy(&raw_time, &tmp_time, sizeof(tmp_time));
  if (raw_time != 0) {
    _this->_internal_set_time(from._internal_time());
  }
  if (from._internal_robot_id() != 0) {
    _this->_internal_set_robot_id(from._internal_robot_id());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = from._internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    _this->_internal_set_x(from._internal_x());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = from._internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    _this->_internal_set_y(from._internal_y());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_battery = from._internal_battery();
  uint32_t raw_battery;
  memcpy(&raw_battery, &tmp_battery, sizeof(tmp_battery));
  if (raw_battery != 0) {
    _this->_internal_set_battery(from._internal_battery());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SimEvent::CopyFrom(const SimEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lastmile.SimEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SimEvent::IsInitialized() const {
  return true;
}

void SimEvent::InternalSwap(SimEvent* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.type_, lhs_arena,
      &other->_impl_.type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.status_, lhs_arena,
      &other->_impl_.status_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.note_, lhs_arena,
      &other->_impl_.note_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SimEvent, _impl_.battery_)
      + sizeof(SimEvent::_impl_.battery_)
      - PROTOBUF_FIELD_OFFSET(SimEvent, _impl_.time_)>(
          reinterpret_cast<char*>(&_impl_.time_),
          reinterpret_cast<char*>(&other->_impl_.time_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SimEvent::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_simulation_2eproto_getter, &descriptor_table_simulation_2eproto_once,
      file_level_metadata_simulation_2eproto[0]);
}

// ===================================================================

class SimStats::_Internal {
 public:
};

SimStats::SimStats(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:lastmile.SimStats)
}
SimStats::SimStats(const SimStats& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SimStats* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.total_energy_kwh_){}
    , decltype(_impl_.total_deliveries_){}
    , decltype(_impl_.recharge_events_){}
    , decltype(_impl_.failed_paths_){}
    , decltype(_impl_.traffic_jams_){}
    , decltype(_impl_.delivery_fails_){}
    , decltype(_impl_.weather_delays_){}
    , decltype(_impl_.parallel_batches_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.total_energy_kwh_, &from._impl_.total_energy_kwh_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.parallel_batches_) -
    reinterpret_cast<char*>(&_impl_.total_energy_kwh_)) + sizeof(_impl_.parallel_batches_));
  // @@protoc_insertion_point(copy_constructor:lastmile.SimStats)
}

inline void SimStats::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.total_energy_kwh_){0}
    , decltype(_impl_.total_deliveries_){0u}
    , decltype(_impl_.recharge_events_){0u}
    , decltype(_impl_.failed_paths_){0u}
    , decltype(_impl_.traffic_jams_){0u}
    , decltype(_impl_.delivery_fails_){0u}
    , decltype(_impl_.weather_delays_){0u}
    , decltype(_impl_.parallel_batches_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SimStats::~SimStats() {
  // @@protoc_insertion_point(destructor:lastmile.SimStats)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SimStats::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SimStats::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SimStats::Clear() {
// @@protoc_insertion_point(message_clear_start:lastmile.SimStats)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.total_energy_kwh_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.parallel_batches_) -
      reinterpret_cast<char*>(&_impl_.total_energy_kwh_)) + sizeof(_impl_.parallel_batches_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SimStats::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 total_deliveries = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.total_deliveries_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double total_energy_kwh = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _impl_.total_energy_kwh_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // uint32 recharge_events = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.recharge_events_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 failed_paths = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.failed_paths_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 traffic_jams = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.traffic_jams_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 delivery_fails = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.delivery_fails_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 weather_delays = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.weather_delays_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 parallel_batches = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.parallel_batches_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SimStats::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lastmile.SimStats)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 total_deliveries = 1;
  if (this->_internal_total_deliveries() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_total_deliveries(), target);
  }

  // double total_energy_kwh = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_total_energy_kwh = this->_internal_total_energy_kwh();
  uint64_t raw_total_energy_kwh;
  memcpy(&raw_total_energy_kwh, &tmp_total_energy_kwh, sizeof(tmp_total_energy_kwh));
  if (raw_total_energy_kwh != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(2, this->_internal_total_energy_kwh(), target);
  }

  // uint32 recharge_events = 3;
  if (this->_internal_recharge_events() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_recharge_events(), target);
  }

  // uint32 failed_paths = 4;
  if (this->_internal_failed_paths() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_failed_paths(), target);
  }

  // uint32 traffic_jams = 5;
  if (this->_internal_traffic_jams() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(5, this->_internal_traffic_jams(), target);
  }

  // uint32 delivery_fails = 6;
  if (this->_internal_delivery_fails() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(6, this->_internal_delivery_fails(), target);
  }

  // uint32 weather_delays = 7;
  if (this->_internal_weather_delays() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(7, this->_internal_weather_delays(), target);
  }

  // uint32 parallel_batches = 8;
  if (this->_internal_parallel_batches() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(8, this->_internal_parallel_batches(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lastmile.SimStats)
  return target;
}

size_t SimStats::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lastmile.SimStats)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double total_energy_kwh = 2;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_total_energy_kwh = this->_internal_total_energy_kwh();
  uint64_t raw_total_energy_kwh;
  memcpy(&raw_total_energy_kwh, &tmp_total_energy_kwh, sizeof(tmp_total_energy_kwh));
  if (raw_total_energy_kwh != 0) {
    total_size += 1 + 8;
  }

  // uint32 total_deliveries = 1;
  if (this->_internal_total_deliveries() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_total_deliveries());
  }

  // uint32 recharge_events = 3;
  if (this->_internal_recharge_events() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_recharge_events());
  }

  // uint32 failed_paths = 4;
  if (this->_internal_failed_paths() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_failed_paths());
  }

  // uint32 traffic_jams = 5;
  if (this->_internal_traffic_jams() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_traffic_jams());
  }

  // uint32 delivery_fails = 6;
  if (this->_internal_delivery_fails() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_delivery_fails());
  }

  // uint32 weather_delays = 7;
  if (this->_internal_weather_delays() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_weather_delays());
  }

  // uint32 parallel_batches = 8;
  if (this->_internal_parallel_batches() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_parallel_batches());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SimStats::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SimStats::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SimStats::GetClassData() const { return &_class_data_; }


void SimStats::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SimStats*>(&to_msg);
  auto& from = static_cast<const SimStats&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lastmile.SimStats)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_total_energy_kwh = from._internal_total_energy_kwh();
  uint64_t raw_total_energy_kwh;
  memcpy(&raw_total_energy_kwh, &tmp_total_energy_kwh, sizeof(tmp_total_energy_kwh));
  if (raw_total_energy_kwh != 0) {
    _this->_internal_set_total_energy_kwh(from._internal_total_energy_kwh());
  }
  if (from._internal_total_deliveries() != 0) {
    _this->_internal_set_total_deliveries(from._internal_total_deliveries());
  }
  if (from._internal_recharge_events() != 0) {
    _this->_internal_set_recharge_events(from._internal_recharge_events());
  }
  if (from._internal_failed_paths() != 0) {
    _this->_internal_set_failed_paths(from._internal_failed_paths());
  }
  if (from._internal_traffic_jams() != 0) {
    _this->_internal_set_traffic_jams(from._internal_traffic_jams());
  }
  if (from._internal_delivery_fails() != 0) {
    _this->_internal_set_delivery_fails(from._internal_delivery_fails());
  }
  if (from._internal_weather_delays() != 0) {
    _this->_internal_set_weather_delays(from._internal_weather_delays());
  }
  if (from._internal_parallel_batches() != 0) {
    _this->_internal_set_parallel_batches(from._internal_parallel_batches());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SimStats::CopyFrom(const SimStats& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lastmile.SimStats)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SimStats::IsInitialized() const {
  return true;
}

void SimStats::InternalSwap(SimStats* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SimStats, _impl_.parallel_batches_)
      + sizeof(SimStats::_impl_.parallel_batches_)
      - PROTOBUF_FIELD_OFFSET(SimStats, _impl_.total_energy_kwh_)>(
          reinterpret_cast<char*>(&_impl_.total_energy_kwh_),
          reinterpret_cast<char*>(&other->_impl_.total_energy_kwh_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SimStats::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_simulation_2eproto_getter, &descriptor_table_simulation_2eproto_once,
      file_level_metadata_simulation_2eproto[1]);
}

// ===================================================================

class SimOutput::_Internal {
 public:
  static const ::lastmile::SimStats& stats(const SimOutput* msg);
};

const ::lastmile::SimStats&
SimOutput::_Internal::stats(const SimOutput* msg) {
  return *msg->_impl_.stats_;
}
SimOutput::SimOutput(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:lastmile.SimOutput)
}
SimOutput::SimOutput(const SimOutput& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SimOutput* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.events_){from._impl_.events_}
    , decltype(_impl_.hub_mode_){}
    , decltype(_impl_.stats_){nullptr}
    , decltype(_impl_.duration_s_){}
    , decltype(_impl_.num_robots_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.hub_mode_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.hub_mode_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_hub_mode().empty()) {
    _this->_impl_.hub_mode_.Set(from._internal_hub_mode(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_stats()) {
    _this->_impl_.stats_ = new ::lastmile::SimStats(*from._impl_.stats_);
  }
  ::memcpy(&_impl_.duration_s_, &from._impl_.duration_s_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.num_robots_) -
    reinterpret_cast<char*>(&_impl_.duration_s_)) + sizeof(_impl_.num_robots_));
  // @@protoc_insertion_point(copy_constructor:lastmile.SimOutput)
}

inline void SimOutput::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.events_){arena}
    , decltype(_impl_.hub_mode_){}
    , decltype(_impl_.stats_){nullptr}
    , decltype(_impl_.duration_s_){0}
    , decltype(_impl_.num_robots_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.hub_mode_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.hub_mode_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SimOutput::~SimOutput() {
  // @@protoc_insertion_point(destructor:lastmile.SimOutput)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SimOutput::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.events_.~RepeatedPtrField();
  _impl_.hub_mode_.Destroy();
  if (this != internal_default_instance()) delete _impl_.stats_;
}

void SimOutput::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SimOutput::Clear() {
// @@protoc_insertion_point(message_clear_start:lastmile.SimOutput)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.events_.Clear();
  _impl_.hub_mode_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.stats_ != nullptr) {
    delete _impl_.stats_;
  }
  _impl_.stats_ = nullptr;
  ::memset(&_impl_.duration_s_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.num_robots_) -
      reinterpret_cast<char*>(&_impl_.duration_s_)) + sizeof(_impl_.num_robots_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SimOutput::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .lastmile.SimEvent events = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_events(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // .lastmile.SimStats stats = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_stats(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 num_robots = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.num_robots_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double duration_s = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _impl_.duration_s_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // string hub_mode = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_hub_mode();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "lastmile.SimOutput.hub_mode"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SimOutput::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:lastmile.SimOutput)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .lastmile.SimEvent events = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_events_size()); i < n; i++) {
    const auto& repfield = this->_internal_events(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // .lastmile.SimStats stats = 2;
  if (this->_internal_has_stats()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::stats(this),
        _Internal::stats(this).GetCachedSize(), target, stream);
  }

  // uint32 num_robots = 3;
  if (this->_internal_num_robots() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_num_robots(), target);
  }

  // double duration_s = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_duration_s = this->_internal_duration_s();
  uint64_t raw_duration_s;
  memcpy(&raw_duration_s, &tmp_duration_s, sizeof(tmp_duration_s));
  if (raw_duration_s != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_duration_s(), target);
  }

  // string hub_mode = 5;
  if (!this->_internal_hub_mode().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_hub_mode().data(), static_cast<int>(this->_internal_hub_mode().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "lastmile.SimOutput.hub_mode");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_hub_mode(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lastmile.SimOutput)
  return target;
}

size_t SimOutput::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:lastmile.SimOutput)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .lastmile.SimEvent events = 1;
  total_size += 1UL * this->_internal_events_size();
  for (const auto& msg : this->_impl_.events_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string hub_mode = 5;
  if (!this->_internal_hub_mode().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_hub_mode());
  }

  // .lastmile.SimStats stats = 2;
  if (this->_internal_has_stats()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.stats_);
  }

  // double duration_s = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_duration_s = this->_internal_duration_s();
  uint64_t raw_duration_s;
  memcpy(&raw_duration_s, &tmp_duration_s, sizeof(tmp_duration_s));
  if (raw_duration_s != 0) {
    total_size += 1 + 8;
  }

  // uint32 num_robots = 3;
  if (this->_internal_num_robots() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_num_robots());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SimOutput::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SimOutput::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SimOutput::GetClassData() const { return &_class_data_; }


void SimOutput::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SimOutput*>(&to_msg);
  auto& from = static_cast<const SimOutput&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:lastmile.SimOutput)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.events_.MergeFrom(from._impl_.events_);
  if (!from._internal_hub_mode().empty()) {
    _this->_internal_set_hub_mode(from._internal_hub_mode());
  }
  if (from._internal_has_stats()) {
    _this->_internal_mutable_stats()->::lastmile::SimStats::MergeFrom(
        from._internal_stats());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_duration_s = from._internal_duration_s();
  uint64_t raw_duration_s;
  memcpy(&raw_duration_s, &tmp_duration_s, sizeof(tmp_duration_s));
  if (raw_duration_s != 0) {
    _this->_internal_set_duration_s(from._internal_duration_s());
  }
  if (from._internal_num_robots() != 0) {
    _this->_internal_set_num_robots(from._internal_num_robots());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SimOutput::CopyFrom(const SimOutput& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:lastmile.SimOutput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SimOutput::IsInitialized() const {
  return true;
}

void SimOutput::InternalSwap(SimOutput* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.events_.InternalSwap(&other->_impl_.events_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.hub_mode_, lhs_arena,
      &other->_impl_.hub_mode_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SimOutput, _impl_.num_robots_)
      + sizeof(SimOutput::_impl_.num_robots_)
      - PROTOBUF_FIELD_OFFSET(SimOutput, _impl_.stats_)>(
          reinterpret_cast<char*>(&_impl_.stats_),
          reinterpret_cast<char*>(&other->_impl_.stats_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SimOutput::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_simulation_2eproto_getter, &descriptor_table_simulation_2eproto_once,
      file_level_metadata_simulation_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace lastmile
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::lastmile::SimEvent*
Arena::CreateMaybeMessage< ::lastmile::SimEvent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::lastmile::SimEvent >(arena);
}
template<> PROTOBUF_NOINLINE ::lastmile::SimStats*
Arena::CreateMaybeMessage< ::lastmile::SimStats >(Arena* arena) {
  return Arena::CreateMessageInternal< ::lastmile::SimStats >(arena);
}
template<> PROTOBUF_NOINLINE ::lastmile::SimOutput*
Arena::CreateMaybeMessage< ::lastmile::SimOutput >(Arena* arena) {
  return Arena::CreateMessageInternal< ::lastmile::SimOutput >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
